import { tool as createTool } from "ai";
import { z } from "zod";
import { resolveImageRefs } from "./image-cache";

/**
 * HTML Preview Tool
 * Displays HTML/CSS/JS code in an interactive iframe preview.
 *
 * Also resolves any "wsp-img://TOKEN" placeholders in the code by
 * substituting the server-cached base64 data URIs before returning,
 * so images generated by fetch_image_as_base64 appear correctly in the preview.
 */
export const htmlPreviewTool = createTool({
  name: "html_preview",
  description:
    "Display HTML, CSS, or JavaScript code with an interactive visual preview. " +
    "Use this when generating web pages, calculators, forms, games, or any interactive UI. " +
    "The code will be rendered in a sandboxed iframe allowing users to interact with it. " +
    "Any wsp-img:// image tokens from fetch_image_as_base64 are automatically resolved.",
  inputSchema: z.object({
    code: z
      .string()
      .describe(
        "The complete HTML/CSS/JS code to preview. For HTML, include inline CSS in <style> tags " +
          "and inline JS in <script> tags for a complete standalone page. " +
          "If you used fetch_image_as_base64, place the returned imageRef tokens directly in src attributes — " +
          "they will be automatically replaced with the real images.",
      ),
    fileType: z
      .enum(["html", "css", "js"])
      .default("html")
      .describe("The type of code file being previewed"),
  }),
  execute: ({ code, fileType }) => {
    // Resolve any wsp-img:// tokens → actual base64 data URIs
    const resolvedCode = resolveImageRefs(code);

    return {
      code: resolvedCode,
      fileType,
      success: true,
    };
  },
});
