import { tool as createTool } from "ai";
import z from "zod";
import logger from "logger";
import { serverFileStorage } from "lib/file-storage";

/**
 * PDF Generator Tool
 * Generates PDFs from text content and provides download links
 * Uses jsPDF for serverless-friendly PDF generation
 */
export const pdfGeneratorTool = createTool({
  name: "generate-pdf",
  description:
    "Generate a PDF document from text content. Returns a downloadable link to the generated PDF.",
  inputSchema: z.object({
    title: z.string().describe("Title of the PDF document"),
    content: z.string().describe("The text content to include in the PDF"),
    filename: z
      .string()
      .optional()
      .describe("Optional filename (without .pdf extension)"),
  }),
  execute: async (
    { title, content, filename },
    { abortSignal: _abortSignal },
  ) => {
    logger.info(`PDF Generator: Creating PDF with title: "${title}"`);

    try {
      // Import jsPDF dynamically
      const { jsPDF } = await import("jspdf");

      // Create PDF document
      const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 15;
      const maxWidth = pageWidth - 2 * margin;
      let yPosition = margin;

      // Add title
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      const titleLines = doc.splitTextToSize(title, maxWidth);
      doc.text(titleLines, margin, yPosition);
      yPosition += titleLines.length * 8 + 5;

      // Add date
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      const dateText = `Generated on ${new Date().toLocaleString()}`;
      doc.text(dateText, margin, yPosition);
      yPosition += 8;

      // Add horizontal line
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 8;

      // Add content with word wrapping
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      const contentLines = doc.splitTextToSize(content, maxWidth);

      for (const line of contentLines) {
        // Check if we need a new page
        if (yPosition + 6 > pageHeight - margin) {
          doc.addPage();
          yPosition = margin;
        }
        doc.text(line, margin, yPosition);
        yPosition += 6;
      }

      // Add footer
      yPosition += 5;
      if (yPosition + 10 > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 5;

      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.text("Generated by Wasp AI", margin, yPosition);

      // Get PDF as buffer
      const pdfBuffer = Buffer.from(doc.output("arraybuffer"));

      logger.info(
        `PDF Generator: PDF created, size: ${pdfBuffer.length} bytes`,
      );

      // Upload to storage
      const pdfFilename =
        filename && !filename.endsWith(".pdf")
          ? `${filename}.pdf`
          : filename || `document-${Date.now()}.pdf`;

      const uploadResult = await serverFileStorage.upload(pdfBuffer, {
        filename: pdfFilename,
        contentType: "application/pdf",
      });

      logger.info(
        `PDF Generator: PDF uploaded successfully to ${uploadResult.sourceUrl}`,
      );

      return {
        success: true,
        downloadUrl: uploadResult.sourceUrl,
        filename: pdfFilename,
        size: pdfBuffer.length,
        guide: `PDF document "${title}" has been generated successfully. You can download it using the link above.`,
      };
    } catch (error) {
      logger.error("PDF Generator Error:", error);
      throw error;
    }
  },
});
