import { tool as createTool } from "ai";
import z from "zod";
import logger from "logger";
import { serverFileStorage } from "lib/file-storage";

/**
 * PDF Generator Tool
 * Generates PDFs from text content and provides download links
 */
export const pdfGeneratorTool = createTool({
  name: "generate-pdf",
  description:
    "Generate a PDF document from text content. Returns a downloadable link to the generated PDF.",
  inputSchema: z.object({
    title: z.string().describe("Title of the PDF document"),
    content: z.string().describe("The text content to include in the PDF"),
    filename: z
      .string()
      .optional()
      .describe("Optional filename (without .pdf extension)"),
  }),
  execute: async ({ title, content, filename }, { abortSignal }) => {
    logger.info(`PDF Generator: Creating PDF with title: "${title}"`);

    try {
      // Import PDFKit dynamically
      const PDFDocument = (await import("pdfkit")).default;

      // Create PDF document in memory
      const doc = new PDFDocument({
        size: "A4",
        margin: 40,
      });

      // Collect PDF data
      const chunks: Buffer[] = [];
      doc.on("data", (chunk: Buffer) => {
        chunks.push(chunk);
      });

      // Add title
      doc.fontSize(24).font("Helvetica-Bold").text(title, { align: "center" });
      doc.moveDown(0.5);

      // Add date
      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`Generated on ${new Date().toLocaleString()}`, {
          align: "center",
        });
      doc.moveDown(1);

      // Add horizontal line
      doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke();
      doc.moveDown(1);

      // Add content with word wrapping
      doc.fontSize(11).font("Helvetica").text(content, {
        align: "left",
        width: 475,
        lineGap: 5,
      });

      // Add footer
      doc.moveDown(1);
      doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke();
      doc.moveDown(0.5);
      doc
        .fontSize(9)
        .font("Helvetica")
        .text("Generated by Better Chatbot", { align: "center" });

      // Finalize PDF
      doc.end();

      // Wait for PDF to be fully generated
      const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
        doc.on("end", () => {
          resolve(Buffer.concat(chunks));
        });
        doc.on("error", reject);

        // Handle abort signal
        if (abortSignal) {
          abortSignal.addEventListener("abort", () => {
            reject(new Error("PDF generation aborted"));
          });
        }
      });

      logger.info(
        `PDF Generator: PDF created, size: ${pdfBuffer.length} bytes`,
      );

      // Upload to storage
      const pdfFilename =
        filename && !filename.endsWith(".pdf")
          ? `${filename}.pdf`
          : filename || `document-${Date.now()}.pdf`;

      const uploadResult = await serverFileStorage.upload(pdfBuffer, {
        filename: pdfFilename,
        contentType: "application/pdf",
      });

      logger.info(
        `PDF Generator: PDF uploaded successfully to ${uploadResult.sourceUrl}`,
      );

      return {
        success: true,
        downloadUrl: uploadResult.sourceUrl,
        filename: pdfFilename,
        size: pdfBuffer.length,
        guide: `PDF document "${title}" has been generated successfully. You can download it using the link above.`,
      };
    } catch (error) {
      logger.error("PDF Generator Error:", error);
      throw error;
    }
  },
});
