import { tool as createTool } from "ai";
import { z } from "zod";

export const PRESENTATION_THEMES = [
  // Modern aesthetic themes from beautiful-html-templates & free-ppt-template
  "bento-modern",
  "acid-brutalist",
  "soft-editorial",
  "editorial-forest",
  "cobalt-grid",
  "black-gold",
  "block-frame",
  "sakura-chroma",
  "8-bit-orbit",
  "broadside",
  "emerald-editorial",
  "studio",
  "capsule",
  "vellum",
  "monochrome",
  "neo-grid-bold",
  "pink-script",
  "pin-and-paper",
  "warm-gradient",
  "minimal-corporate",
  "cyber-neon",
  // Legacy aliases for backwards-compatibility
  "tech",
  "business",
  "creative",
  "education",
  "nature",
  "medical",
  "energy",
  "elegant",
] as const;

export type PresentationThemeName = (typeof PRESENTATION_THEMES)[number];

export interface NormalizedSlide {
  type: string;
  title: string;
  subtitle?: string;
  tagline?: string;
  points?: string[];
  left?: { heading: string; points: string[] };
  right?: { heading: string; points: string[] };
  stat?: string;
  description?: string;
  icon?: string;
  content?: string;
  columns?: Array<{ heading: string; points: string[] }>;
  timeline?: Array<{ year: string; event: string }>;
  quote?: string;
  attribution?: string;
  items?: Array<{ text: string; checked: boolean }>;
  heading?: string;
  cta?: string;
}

/**
 * Strip common markdown formatting characters from a plain text string so
 * raw LLM output (e.g. "# Heading", "**Bold**", "- bullet") never bleeds
 * into the actual slide text rendered by pptxgenjs.
 */
export function stripMd(s: string): string {
  if (!s) return "";
  return (
    s
      // Remove leading heading hashes: ## Title → Title
      .replace(/^#+\s*/gm, "")
      // Remove bold/italic markers: **text**, __text__, *text*, _text_
      .replace(/(\*\*|__)(.*?)\1/g, "$2")
      .replace(/(\*|_)(.*?)\1/g, "$2")
      // Remove inline code: `code`
      .replace(/`([^`]*)`/g, "$1")
      // Remove leading bullet/dash/numbered list chars at line start
      .replace(/^[-*+]\s+/gm, "")
      .replace(/^\d+\.\s+/gm, "")
      // Collapse multiple blank lines to one and trim
      .replace(/\n{2,}/g, " ")
      .trim()
  );
}

export function normalizePresentationPayload(raw: any) {
  if (!raw || typeof raw !== "object") {
    return {
      title: "Executive Presentation",
      description: "Presentation Deck",
      topic: "General",
      theme: "bento-modern" as PresentationThemeName,
      slides: [
        {
          type: "cover",
          title: "Executive Presentation",
          subtitle: "Generated by Wasp AI",
          tagline: "High-impact presentation",
        },
      ],
    };
  }

  // 1. Accept either 'slides' or 'sections'
  let slidesRaw = raw.slides;
  if (!Array.isArray(slidesRaw) && Array.isArray(raw.sections)) {
    slidesRaw = raw.sections;
  }
  if (typeof slidesRaw === "string") {
    try {
      slidesRaw = JSON.parse(slidesRaw);
    } catch {
      slidesRaw = [];
    }
  }
  if (!Array.isArray(slidesRaw)) {
    slidesRaw = [];
  }

  // 2. Normalize theme
  const themeName = String(raw.theme || "")
    .toLowerCase()
    .trim();
  const validTheme = PRESENTATION_THEMES.find(
    (t) => t.toLowerCase() === themeName,
  );
  const theme: PresentationThemeName = validTheme || "bento-modern";

  // 3. Normalize slides
  const normalizedSlides: NormalizedSlide[] = slidesRaw.map(
    (s: any, idx: number) => {
      if (!s || typeof s !== "object") {
        return {
          type: "bullet-list",
          title: `Slide ${idx + 1}`,
          points: [stripMd(String(s || "Key point"))],
        };
      }

      const rawType = String(s.type || s.layout || "")
        .toLowerCase()
        .trim();
      const title = stripMd(
        String(s.title || s.heading || `Slide ${idx + 1}`).trim(),
      );

      // Extract points safely from points array, string, or content — strip markdown from each
      let points: string[] = [];
      if (Array.isArray(s.points)) {
        points = s.points
          .map((p: any) => stripMd(String(p)))
          .filter((p) => p.trim().length > 0);
      } else if (typeof s.points === "string") {
        points = s.points
          .split(/\n|•|- /)
          .map((p: string) => stripMd(p.trim()))
          .filter(Boolean);
      } else if (typeof s.content === "string") {
        points = s.content
          .split(/\n|•|- /)
          .map((p: string) => stripMd(p.trim()))
          .filter(Boolean);
        if (points.length === 0 && s.content.trim()) {
          points = [stripMd(s.content.trim())];
        }
      }

      // ── Cover-rescue heuristic ─────────────────────────────────────────────
      // If the first slide has a generic boilerplate title like "Title Slide",
      // "Cover", or "Title" (a tell that the AI put the real title inside the
      // points array instead), reconstruct it as a proper cover slide.
      // Also handles the case where rawType is explicitly "cover" but fields
      // such as subtitle/tagline are missing yet the real title is in points.
      const isFirstSlide = idx === 0;
      const isGenericCoverTitle =
        /^(title\s*slide|cover(\s*slide)?|title)$/i.test(title.trim());

      if (isFirstSlide && (isGenericCoverTitle || rawType === "cover")) {
        // If title is a placeholder, promote points[0] to the real title
        const realTitle = isGenericCoverTitle
          ? points.length > 0
            ? points[0]
            : stripMd(String(raw.title || "Presentation"))
          : title;

        const remainingPoints = isGenericCoverTitle ? points.slice(1) : points;
        const subtitleCandidate =
          remainingPoints
            .filter((p) => !/^(date|prepared\s*for|date:)/i.test(p))
            .join(" · ") || stripMd(String(raw.description || ""));

        const dateCandidate =
          remainingPoints
            .find((p) => /^(date|date:)/i.test(p))
            ?.replace(/^date:\s*/i, "") ||
          stripMd(String(s.subtitle || s.tagline || raw.description || ""));

        return {
          type: "cover",
          title: realTitle || stripMd(String(raw.title || "Presentation")),
          subtitle: subtitleCandidate,
          tagline: dateCandidate || "Created with Wasp AI",
        };
      }

      // Infer slide type if omitted or unknown
      let type = rawType;
      if (!type) {
        if (s.stat || s.value) type = "big-stat";
        else if (s.quote) type = "quote";
        else if (s.timeline) type = "timeline";
        else if (s.items) type = "checklist";
        else if (s.left || s.right) type = "two-column";
        else if (s.columns) type = "three-column";
        else if (
          idx === 0 &&
          (s.subtitle || s.tagline) &&
          !s.content &&
          !s.points
        )
          type = "cover";
        else if (idx === slidesRaw.length - 1 && (s.cta || s.heading))
          type = "call-to-action";
        else type = "bullet-list";
      }

      if (type === "cover") {
        return {
          type: "cover",
          title: title || stripMd(String(raw.title || "Presentation Title")),
          subtitle: stripMd(
            String(s.subtitle || s.description || raw.description || ""),
          ),
          tagline: stripMd(
            String(s.tagline || s.subtitle || "Created with Wasp AI"),
          ),
        };
      }

      if (type === "two-column") {
        let left = s.left;
        let right = s.right;
        if (!left || typeof left !== "object") {
          const half = Math.ceil(points.length / 2);
          left = {
            heading: "Key Highlights",
            points:
              points.slice(0, half).length > 0
                ? points.slice(0, half)
                : ["Overview point"],
          };
        } else {
          left = {
            heading: stripMd(String(left.heading || "Key Points")),
            points: Array.isArray(left.points)
              ? left.points.map((p: any) => stripMd(String(p)))
              : Array.isArray(left)
                ? left.map((p: any) => stripMd(String(p)))
                : [stripMd(String(left.points || left || "Point"))],
          };
        }

        if (!right || typeof right !== "object") {
          const half = Math.ceil(points.length / 2);
          right = {
            heading: "Analysis & Impact",
            points:
              points.slice(half).length > 0
                ? points.slice(half)
                : ["Impact point"],
          };
        } else {
          right = {
            heading: stripMd(String(right.heading || "Key Points")),
            points: Array.isArray(right.points)
              ? right.points.map((p: any) => stripMd(String(p)))
              : Array.isArray(right)
                ? right.map((p: any) => stripMd(String(p)))
                : [stripMd(String(right.points || right || "Point"))],
          };
        }

        return {
          type: "two-column",
          title,
          left,
          right,
        };
      }

      if (type === "three-column") {
        let cols = s.columns;
        if (!Array.isArray(cols) || cols.length === 0) {
          cols = [
            {
              heading: "Pillar 1",
              points:
                points.slice(0, 2).length > 0
                  ? points.slice(0, 2)
                  : ["Core aspect"],
            },
            {
              heading: "Pillar 2",
              points:
                points.slice(2, 4).length > 0
                  ? points.slice(2, 4)
                  : ["Execution aspect"],
            },
            {
              heading: "Pillar 3",
              points:
                points.slice(4, 6).length > 0
                  ? points.slice(4, 6)
                  : ["Outcome aspect"],
            },
          ];
        }
        return {
          type: "three-column",
          title,
          columns: cols.slice(0, 3).map((col: any, cIdx: number) => ({
            heading: stripMd(String(col?.heading || `Pillar ${cIdx + 1}`)),
            points: Array.isArray(col?.points)
              ? col.points.map((p: any) => stripMd(String(p)))
              : [stripMd(String(col?.points || col || "Detail"))],
          })),
        };
      }

      if (type === "big-stat") {
        return {
          type: "big-stat",
          title,
          stat: stripMd(String(s.stat || s.value || "Top Tier")),
          description: stripMd(
            String(
              s.description ||
                s.content ||
                points.join(". ") ||
                "Key industry metric",
            ),
          ),
        };
      }

      if (type === "content-with-icon") {
        return {
          type: "content-with-icon",
          title,
          icon: String(s.icon || "Sparkles"),
          content: stripMd(
            String(
              s.content ||
                points.join(". ") ||
                "Essential capability highlight.",
            ),
          ),
        };
      }

      if (type === "timeline") {
        let timeline = s.timeline;
        if (!Array.isArray(timeline) || timeline.length === 0) {
          timeline = points.map((p, pIdx) => ({
            year: `Phase ${pIdx + 1}`,
            event: p,
          }));
        }
        if (timeline.length === 0) {
          timeline = [
            { year: "Phase 1", event: "Discovery & Planning" },
            { year: "Phase 2", event: "Development & Scaling" },
            { year: "Phase 3", event: "Deployment & Market Leadership" },
          ];
        }
        return {
          type: "timeline",
          title,
          timeline: timeline.map((item: any, tIdx: number) => ({
            year: stripMd(String(item?.year || `Phase ${tIdx + 1}`)),
            event: stripMd(
              String(item?.event || item?.description || item || "Milestone"),
            ),
          })),
        };
      }

      if (type === "quote") {
        return {
          type: "quote",
          title,
          quote: stripMd(String(s.quote || s.content || title)),
          attribution: stripMd(
            String(s.attribution || s.author || "Industry Benchmark"),
          ),
        };
      }

      if (type === "checklist") {
        let items = s.items;
        if (!Array.isArray(items) || items.length === 0) {
          items = points.map((p) => ({ text: p, checked: true }));
        }
        if (items.length === 0) {
          items = [
            { text: "Verified capability", checked: true },
            { text: "Production readiness", checked: true },
            { text: "Ongoing optimization", checked: true },
          ];
        }
        return {
          type: "checklist",
          title,
          items: items.map((item: any) => ({
            text: stripMd(String(item?.text || item || "Action item")),
            checked: typeof item?.checked === "boolean" ? item.checked : true,
          })),
        };
      }

      if (type === "call-to-action") {
        return {
          type: "call-to-action",
          title,
          heading: stripMd(String(s.heading || title)),
          cta: stripMd(String(s.cta || "Get Started")),
          description: stripMd(
            String(
              s.description ||
                s.content ||
                points.join(". ") ||
                "Take the next step.",
            ),
          ),
        };
      }

      // Default: bullet-list
      return {
        type: "bullet-list",
        title,
        points: points.length > 0 ? points : ["Key takeaway point"],
      };
    },
  );

  // If slides array was completely empty, populate cover slide
  if (normalizedSlides.length === 0) {
    normalizedSlides.push({
      type: "cover",
      title: stripMd(String(raw.title || "Executive Presentation")),
      subtitle: stripMd(String(raw.description || "Comprehensive Overview")),
      tagline: "Created with Wasp AI",
    });
  }

  return {
    title: stripMd(String(raw.title || "Executive Presentation")),
    description: stripMd(
      String(raw.description || raw.topic || "Presentation Deck"),
    ),
    topic: String(raw.topic || raw.title || "General"),
    theme,
    slides: normalizedSlides,
  };
}

export const presentationInputSchema = z
  .object({
    title: z.string().optional().describe("Overall presentation title"),
    description: z.string().optional().describe("Brief tagline/summary"),
    topic: z.string().optional().describe("Topic of the presentation"),
    theme: z
      .string()
      .optional()
      .describe(
        "Aesthetic theme: bento-modern, acid-brutalist, black-gold, soft-editorial, editorial-forest, cobalt-grid, block-frame, sakura-chroma, 8-bit-orbit, broadside, emerald-editorial, studio, capsule, vellum, monochrome, neo-grid-bold, pink-script, pin-and-paper, warm-gradient, minimal-corporate, cyber-neon",
      ),
    slides: z
      .array(z.any())
      .optional()
      .describe("Array of slides (6 to 10 slides recommended)"),
    sections: z
      .array(z.any())
      .optional()
      .describe("Alternative format: array of sections/slides"),
  })
  .transform((data) => normalizePresentationPayload(data));

export const presentationGeneratorTool = createTool({
  description:
    "Generate a professional PowerPoint presentation deck (6-10 slides) with curated aesthetic themes and dynamic layout types. Accepts 'slides' or 'sections'. For real-time topics, current year rankings, or factual news, invoke the web-search tool first to gather verified data before calling this tool.",
  inputSchema: presentationInputSchema,
  execute: async (args) => {
    const normalized = normalizePresentationPayload(args);
    // Simply return the normalized data to the client for browser-side PPTX generation & preview
    return {
      success: true,
      ...normalized,
      generatedAt: new Date().toISOString(),
      status: "ready_for_browser_generation",
    };
  },
});
