import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Wasp AI",
  description: "Terms of Service for Wasp AI Solutions. Last updated January 2026.",
};

export default function TermsPage() {
  return (
    <div className="container max-w-4xl py-12 px-4 mx-auto">
      <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
      <p className="text-muted-foreground mb-8">Last Updated: January 17, 2026</p>

      <div className="prose dark:prose-invert max-w-none space-y-8">
        <section>
          <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing and using <strong>Wasp AI Solutions</strong> (&quot;Service&quot;), you accept and agree to be bound by the terms and provision of this agreement. In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable to such services.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
          <p>
            Wasp AI is a multi-model AI platform providing access to various Large Language Models (LLMs), image generation tools, and utility features. You understand and agree that the Service is provided &quot;AS-IS&quot; and that Wasp AI assumes no responsibility for the timeliness, deletion, mis-delivery or failure to store any user communications or personalization settings.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">3. User Conduct</h2>
          <p>You agree to not use the Service to:</p>
          <ul className="list-disc pl-6 space-y-2 mt-2">
            <li>Generate content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or libellous.</li>
            <li>Generate content that promotes discrimination, hatred, or violence.</li>
            <li>Impersonate any person or entity.</li>
            <li>Upload any material that contains software viruses or any other computer code designed to interrupt, destroy or limit the functionality of any computer software or hardware.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">4. AI-Generated Content</h2>
          <p>
            You acknowledge that the output provided by our AI models is generated by artificial intelligence. We make no guarantees regarding the accuracy, currency, or quality of any AI-generated content. You are solely responsible for how you use the generated content.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">5. Intellectual Property</h2>
          <p>
            The Wasp AI interface, logo, and proprietary code are the intellectual property of Wasp AI Solutions. Content you generate using the platform belongs to you, subject to the terms of the underlying model providers (e.g., OpenAI, Google, Anthropic).
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">6. Termination</h2>
          <p>
            We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">7. Contact Information</h2>
          <p>
            Any questions about the Terms of Service should be addressed to <a href="mailto:support@waspai.in" className="text-primary hover:underline">support@waspai.in</a>.
          </p>
        </section>
      </div>
    </div>
  );
}
