export interface WoinoVoice {
  id: string;
  name: string;
  lang: string;
  gender: "male" | "female";
  accent: string;
}

export const WOINO_VOICES: WoinoVoice[] = [
  {
    id: "aadhav",
    name: "Aadhav",
    lang: "kannada",
    gender: "male",
    accent: "indian",
  },
  {
    id: "aadya",
    name: "Aadya",
    lang: "bengali",
    gender: "female",
    accent: "indian",
  },
  {
    id: "aanya",
    name: "Aanya",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "aarush",
    name: "Aarush",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "aarushi",
    name: "Aarushi",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "abir",
    name: "Abir",
    lang: "bengali",
    gender: "male",
    accent: "indian",
  },
  {
    id: "aditi",
    name: "Aditi",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "advika",
    name: "Advika",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "aisha",
    name: "Aisha",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "alba",
    name: "Alba",
    lang: "spanish",
    gender: "female",
    accent: "standard",
  },
  {
    id: "albus",
    name: "Albus",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "alec",
    name: "Alec",
    lang: "english",
    gender: "male",
    accent: "canadian",
  },
  {
    id: "alex",
    name: "Alex",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "alistair",
    name: "Alistair",
    lang: "english",
    gender: "male",
    accent: "british",
  },
  {
    id: "amaira",
    name: "Amaira",
    lang: "bengali",
    gender: "female",
    accent: "indian",
  },
  {
    id: "andrea",
    name: "Andrea",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "aneer",
    name: "Aneer",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "anika",
    name: "Anika",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "anitha",
    name: "Anitha",
    lang: "tamil",
    gender: "female",
    accent: "tamil",
  },
  {
    id: "anuja",
    name: "Anuja",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "arjun",
    name: "Arjun",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "arnab",
    name: "Arnab",
    lang: "bengali",
    gender: "male",
    accent: "indian",
  },
  {
    id: "arun",
    name: "Arun",
    lang: "kannada",
    gender: "male",
    accent: "indian",
  },
  {
    id: "ashwin",
    name: "Ashwin",
    lang: "kannada",
    gender: "male",
    accent: "indian",
  },
  {
    id: "atharv",
    name: "Atharv",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "avery",
    name: "Avery",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "avni",
    name: "Avni",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "balwinder",
    name: "Balwinder",
    lang: "bengali",
    gender: "male",
    accent: "indian",
  },
  {
    id: "bellatrix",
    name: "Bellatrix",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "blofeld",
    name: "Blofeld",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "brian",
    name: "Brian",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "brooke",
    name: "Brooke",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "camilla",
    name: "Camilla",
    lang: "spanish",
    gender: "female",
    accent: "mexican/latin",
  },
  {
    id: "carlos",
    name: "Carlos",
    lang: "spanish",
    gender: "male",
    accent: "mexican/latin",
  },
  {
    id: "chandana",
    name: "Chandana",
    lang: "kannada",
    gender: "female",
    accent: "kannada",
  },
  {
    id: "chinmay",
    name: "Chinmay",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "chinmayi",
    name: "Chinmayi",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "chirag",
    name: "Chirag",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "chloe",
    name: "Chloe",
    lang: "english",
    gender: "female",
    accent: "australian",
  },
  {
    id: "cooper",
    name: "Cooper",
    lang: "english",
    gender: "male",
    accent: "australian",
  },
  {
    id: "daniel",
    name: "Daniel",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "daniella",
    name: "Daniella",
    lang: "spanish",
    gender: "female",
    accent: "mexican/latin",
  },
  {
    id: "david",
    name: "David",
    lang: "spanish",
    gender: "male",
    accent: "standard",
  },
  {
    id: "debashis",
    name: "Debashis",
    lang: "bengali",
    gender: "male",
    accent: "indian",
  },
  {
    id: "deepashri",
    name: "Deepashri",
    lang: "kannada",
    gender: "female",
    accent: "kannada",
  },
  {
    id: "devansh",
    name: "Devansh",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "dhruv",
    name: "Dhruv",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "dhruvit",
    name: "Dhruvit",
    lang: "gujarati",
    gender: "male",
    accent: "gujarati",
  },
  {
    id: "diego",
    name: "Diego",
    lang: "spanish",
    gender: "male",
    accent: "mexican/latin",
  },
  {
    id: "dina",
    name: "Dina",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "divya",
    name: "Divya",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "edward",
    name: "Edward",
    lang: "english",
    gender: "male",
    accent: "british",
  },
  {
    id: "elizabeth",
    name: "Elizabeth",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "emilio",
    name: "Emilio",
    lang: "spanish",
    gender: "male",
    accent: "mexican-latin-american",
  },
  {
    id: "erica",
    name: "Erica",
    lang: "english",
    gender: "female",
    accent: "canadian",
  },
  {
    id: "ethan",
    name: "Ethan",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "felix",
    name: "Felix",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "flynn",
    name: "Flynn",
    lang: "english",
    gender: "male",
    accent: "australian",
  },
  {
    id: "gabriela",
    name: "Gabriela",
    lang: "spanish",
    gender: "female",
    accent: "mexican/latin",
  },
  {
    id: "ganya",
    name: "Ganya",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "gargi",
    name: "Gargi",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "gaurav",
    name: "Gaurav",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "gauri",
    name: "Gauri",
    lang: "marathi",
    gender: "female",
    accent: "marathi",
  },
  {
    id: "girish",
    name: "Girish",
    lang: "kannada",
    gender: "male",
    accent: "standard",
  },
  {
    id: "gurpreet",
    name: "Gurpreet",
    lang: "punjabi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "hannah",
    name: "Hannah",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "harish",
    name: "Harish",
    lang: "kannada",
    gender: "male",
    accent: "indian",
  },
  {
    id: "harjot",
    name: "Harjot",
    lang: "punjabi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "harleen",
    name: "Harleen",
    lang: "bengali",
    gender: "female",
    accent: "indian",
  },
  {
    id: "harper",
    name: "Harper",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "harsh",
    name: "Harsh",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "harshita",
    name: "Harshita",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "hitesh",
    name: "Hitesh",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "ilsa",
    name: "Ilsa",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "imogen",
    name: "Imogen",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "irisha",
    name: "Irisha",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "isabella",
    name: "Isabella",
    lang: "spanish",
    gender: "female",
    accent: "mexican-latin-american",
  },
  {
    id: "ishan",
    name: "Ishan",
    lang: "bengali",
    gender: "male",
    accent: "indian",
  },
  {
    id: "ishani",
    name: "Ishani",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "jaspal",
    name: "Jaspal",
    lang: "bengali",
    gender: "male",
    accent: "indian",
  },
  {
    id: "javier",
    name: "Javier",
    lang: "spanish",
    gender: "male",
    accent: "mexican/latin",
  },
  {
    id: "jeevan",
    name: "Jeevan",
    lang: "tamil",
    gender: "male",
    accent: "tamil",
  },
  {
    id: "jessica",
    name: "Jessica",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "john",
    name: "John",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "johnny",
    name: "Johnny",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "jordan",
    name: "Jordan",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "jose",
    name: "José",
    lang: "spanish",
    gender: "male",
    accent: "mexican/latin",
  },
  {
    id: "julia",
    name: "Julia",
    lang: "english",
    gender: "female",
    accent: "british",
  },
  {
    id: "karan",
    name: "Karan",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "kartik",
    name: "Kartik",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "kaustubh",
    name: "Kaustubh",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "kavya",
    name: "Kavya",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "khushi",
    name: "Khushi",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "kiara",
    name: "Kiara",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "kiran",
    name: "Kiran",
    lang: "gujarati",
    gender: "female",
    accent: "gujarati",
  },
  {
    id: "krish",
    name: "Krish",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "kunal",
    name: "Kunal",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "kyle",
    name: "Kyle",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "lakshya",
    name: "Lakshya",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "lauren",
    name: "Lauren",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "lavanya",
    name: "Lavanya",
    lang: "kannada",
    gender: "female",
    accent: "telugu",
  },
  {
    id: "liam",
    name: "Liam",
    lang: "english",
    gender: "male",
    accent: "british",
  },
  {
    id: "lokesh",
    name: "Lokesh",
    lang: "kannada",
    gender: "male",
    accent: "telugu",
  },
  {
    id: "lucas",
    name: "Lucas",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "lucia",
    name: "Lucia",
    lang: "spanish",
    gender: "female",
    accent: "mexican/latin",
  },
  {
    id: "luis",
    name: "Luis",
    lang: "spanish",
    gender: "male",
    accent: "mexican/latin",
  },
  {
    id: "luther",
    name: "Luther",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "magnus",
    name: "Magnus",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "mahesh",
    name: "Mahesh",
    lang: "kannada",
    gender: "male",
    accent: "telugu",
  },
  {
    id: "maithili",
    name: "Maithili",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "malcolm",
    name: "Malcolm",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "manjunath",
    name: "Manjunath",
    lang: "kannada",
    gender: "male",
    accent: "kannada",
  },
  {
    id: "marcos",
    name: "Marcos",
    lang: "spanish",
    gender: "male",
    accent: "standard",
  },
  {
    id: "mariana",
    name: "Mariana",
    lang: "spanish",
    gender: "female",
    accent: "mexican/latin",
  },
  {
    id: "maya",
    name: "Maya",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "meera",
    name: "Meera",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "mia",
    name: "Mia",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "miguel",
    name: "Miguel",
    lang: "spanish",
    gender: "male",
    accent: "mexican/latin",
  },
  {
    id: "mihir",
    name: "Mihir",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "mohit",
    name: "Mohit",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "mughda",
    name: "Mughda",
    lang: "marathi",
    gender: "female",
    accent: "marathi",
  },
  {
    id: "myra",
    name: "Myra",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "naina",
    name: "Naina",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "nandini",
    name: "Nandini",
    lang: "kannada",
    gender: "female",
    accent: "kannada",
  },
  {
    id: "natasha",
    name: "Natasha",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "navdeep",
    name: "Navdeep",
    lang: "bengali",
    gender: "male",
    accent: "indian",
  },
  {
    id: "navya",
    name: "Navya",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "neel",
    name: "Neel",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "nerea",
    name: "Nerea",
    lang: "spanish",
    gender: "female",
    accent: "standard",
  },
  {
    id: "nicole",
    name: "Nicole",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "niharika",
    name: "Niharika",
    lang: "gujarati",
    gender: "female",
    accent: "gujarati",
  },
  {
    id: "nikita",
    name: "Nikita",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "nilesh",
    name: "Nilesh",
    lang: "hindi",
    gender: "male",
    accent: "marathi",
  },
  {
    id: "nirav",
    name: "Nirav",
    lang: "gujarati",
    gender: "male",
    accent: "gujarati",
  },
  {
    id: "nirupma",
    name: "Nirupma",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "nithya",
    name: "Nithya",
    lang: "kannada",
    gender: "male",
    accent: "indian",
  },
  {
    id: "noah",
    name: "Noah",
    lang: "english",
    gender: "male",
    accent: "british",
  },
  {
    id: "olivia",
    name: "Olivia",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "padmaja",
    name: "Padmaja",
    lang: "telugu",
    gender: "female",
    accent: "telugu",
  },
  {
    id: "parth",
    name: "Parth",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "paulina",
    name: "Paulina",
    lang: "spanish",
    gender: "female",
    accent: "mexican-latin-american",
  },
  {
    id: "poppy",
    name: "Poppy",
    lang: "english",
    gender: "female",
    accent: "british",
  },
  {
    id: "prachi",
    name: "Prachi",
    lang: "gujarati",
    gender: "female",
    accent: "gujarati",
  },
  {
    id: "pranav",
    name: "Pranav",
    lang: "kannada",
    gender: "male",
    accent: "kannada",
  },
  {
    id: "prashanth",
    name: "Prashanth",
    lang: "kannada",
    gender: "male",
    accent: "kannada",
  },
  {
    id: "pritam",
    name: "Pritam",
    lang: "bengali",
    gender: "male",
    accent: "indian",
  },
  {
    id: "priyanka",
    name: "Priyanka",
    lang: "marathi",
    gender: "female",
    accent: "marathi",
  },
  {
    id: "quinn",
    name: "Quinn",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "rachel",
    name: "Rachel",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "radhika",
    name: "Radhika",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "rajan",
    name: "Rajan",
    lang: "kannada",
    gender: "male",
    accent: "indian",
  },
  {
    id: "rajeshwari",
    name: "Rajeshwari",
    lang: "tamil",
    gender: "female",
    accent: "tamil",
  },
  {
    id: "ram",
    name: "Ram",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "ranbir",
    name: "Ranbir",
    lang: "bengali",
    gender: "male",
    accent: "indian",
  },
  {
    id: "rehan",
    name: "Rehan",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "reva",
    name: "Reva",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "reyan",
    name: "Reyan",
    lang: "kannada",
    gender: "male",
    accent: "indian",
  },
  {
    id: "rishika",
    name: "Rishika",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "robert",
    name: "Robert",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "rodrigo",
    name: "Rodrigo",
    lang: "spanish",
    gender: "male",
    accent: "mexican-latin-american",
  },
  {
    id: "ronald",
    name: "Ronald",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "rupali",
    name: "Rupali",
    lang: "marathi",
    gender: "female",
    accent: "marathi",
  },
  {
    id: "ryan",
    name: "Ryan",
    lang: "english",
    gender: "male",
    accent: "american",
  },
  {
    id: "saanvi",
    name: "Saanvi",
    lang: "marathi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "sakshi",
    name: "Sakshi",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "samarth",
    name: "Samarth",
    lang: "bengali",
    gender: "male",
    accent: "indian",
  },
  {
    id: "sana",
    name: "Sana",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "sandhya",
    name: "Sandhya",
    lang: "tamil",
    gender: "female",
    accent: "tamil",
  },
  {
    id: "sandra",
    name: "Sandra",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "sanjay",
    name: "Sanjay",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "sanket",
    name: "Sanket",
    lang: "marathi",
    gender: "male",
    accent: "marathi",
  },
  {
    id: "sayali",
    name: "Sayali",
    lang: "marathi",
    gender: "female",
    accent: "marathi",
  },
  {
    id: "shibi",
    name: "Shibi",
    lang: "malayalam",
    gender: "male",
    accent: "malayalam",
  },
  {
    id: "shivangi",
    name: "Shivangi",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "shreyas",
    name: "Shreyas",
    lang: "kannada",
    gender: "male",
    accent: "indian",
  },
  {
    id: "shrihari",
    name: "Shrihari",
    lang: "telugu",
    gender: "male",
    accent: "telugu",
  },
  {
    id: "shruthi",
    name: "Shruthi",
    lang: "kannada",
    gender: "female",
    accent: "kannada",
  },
  {
    id: "siddharth",
    name: "Siddharth",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "sienna",
    name: "Sienna",
    lang: "english",
    gender: "female",
    accent: "australian",
  },
  {
    id: "simran",
    name: "Simran",
    lang: "punjabi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "siya",
    name: "Siya",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "sophia",
    name: "Sophia",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "soumya",
    name: "Soumya",
    lang: "bengali",
    gender: "female",
    accent: "indian",
  },
  {
    id: "souvik",
    name: "Souvik",
    lang: "bengali",
    gender: "male",
    accent: "indian",
  },
  {
    id: "sridhar",
    name: "Sridhar",
    lang: "kannada",
    gender: "male",
    accent: "telugu",
  },
  {
    id: "srikanth",
    name: "Srikanth",
    lang: "kannada",
    gender: "male",
    accent: "telugu",
  },
  {
    id: "srishti",
    name: "Srishti",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "sudarshan",
    name: "Sudarshan",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "sunidhi",
    name: "Sunidhi",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "surya",
    name: "Surya",
    lang: "kannada",
    gender: "male",
    accent: "indian",
  },
  {
    id: "tanvi",
    name: "Tanvi",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "tara",
    name: "Tara",
    lang: "english",
    gender: "female",
    accent: "neutral",
  },
  {
    id: "teja",
    name: "Teja",
    lang: "kannada",
    gender: "male",
    accent: "telugu",
  },
  {
    id: "tyler",
    name: "Tyler",
    lang: "english",
    gender: "male",
    accent: "standard",
  },
  {
    id: "vaibhav",
    name: "Vaibhav",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "vaisakh",
    name: "Vaisakh",
    lang: "malayalam",
    gender: "male",
    accent: "malayalam",
  },
  {
    id: "vaishnavi",
    name: "Vaishnavi",
    lang: "marathi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "vanessa",
    name: "Vanessa",
    lang: "english",
    gender: "female",
    accent: "american",
  },
  {
    id: "vedant",
    name: "Vedant",
    lang: "bengali",
    gender: "male",
    accent: "indian",
  },
  {
    id: "veer",
    name: "Veer",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "venkat",
    name: "Venkat",
    lang: "kannada",
    gender: "male",
    accent: "indian",
  },
  {
    id: "vikram",
    name: "Vikram",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "vinay",
    name: "Vinay",
    lang: "kannada",
    gender: "male",
    accent: "kannada",
  },
  {
    id: "virat",
    name: "Virat",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "vivaan",
    name: "Vivaan",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "wasim",
    name: "Wasim",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "william",
    name: "William",
    lang: "english",
    gender: "male",
    accent: "canadian",
  },
  {
    id: "yash",
    name: "Yash",
    lang: "hindi",
    gender: "male",
    accent: "indian",
  },
  {
    id: "yuvan",
    name: "Yuvan",
    lang: "bengali",
    gender: "male",
    accent: "indian",
  },
  {
    id: "yuvika",
    name: "Yuvika",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
  {
    id: "zorin",
    name: "Zorin",
    lang: "english",
    gender: "male",
    accent: "standard",
  },
  {
    id: "zoya",
    name: "Zoya",
    lang: "hindi",
    gender: "female",
    accent: "indian",
  },
];

export const WOINO_VOICE_MAP = new Map<string, WoinoVoice>(
  WOINO_VOICES.map((v) => [v.id, v]),
);

export const WOINO_VOICE_IDS = new Set<string>(WOINO_VOICES.map((v) => v.id));

export const WOINO_ALIASES: Record<string, string> = {
  woino: "aditi",
  "woino-default": "aditi",
  "woino-female": "aditi",
  "woino-male": "aarush",
  "woino-hindi": "aditi",
  "woino-english": "magnus",
};

export function resolveWoinoVoiceId(voice: string): string {
  if (!voice) return "aditi";
  if (WOINO_ALIASES[voice]) return WOINO_ALIASES[voice];
  if (voice.startsWith("woino-")) {
    const sub = voice.slice(6);
    if (WOINO_ALIASES[sub]) return WOINO_ALIASES[sub];
    return sub;
  }
  return voice;
}

export function isWoinoVoice(voice: string): boolean {
  if (!voice) return false;
  if (voice === "woino" || WOINO_ALIASES[voice]) return true;
  const bareId = resolveWoinoVoiceId(voice);
  return WOINO_VOICE_IDS.has(bareId);
}

export function getWoinoVoice(voice: string): WoinoVoice | undefined {
  const bareId = resolveWoinoVoiceId(voice);
  return WOINO_VOICE_MAP.get(bareId);
}
